language: node_js

services:
  - docker

env:
  global:
    - NODE_ENV=production
    - FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
    - FIREBASE_PRIVATE_KEY_ID=$FIREBASE_PRIVATE_KEY_ID
    - FIREBASE_PRIVATE_KEY=$FIREBASE_PRIVATE_KEY
    - FIREBASE_CLIENT_EMAIL=$FIREBASE_CLIENT_EMAIL
    - FIREBASE_CLIENT_ID=$FIREBASE_CLIENT_ID

before_install:
  - npm install -g nodemon
  - npm install
  - npm start

script: npm test
