language: node_js

services:
  - docker

env:
  - NODE_ENV= production
  - FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
  - FIREBASE_PRIVATE_KEY_ID=$FIREBASE_PRIVATE_KEY_ID
  - FIREBASE_PRIVATE_KEY=$FIREBASE_PRIVATE_KEY
  - FIREBASE_CLIENT_EMAIL=$FIREBASE_CLIENT_EMAIL
  - FIREBASE_CLIENT_ID=$FIREBASE_CLIENT_ID

before_install:
  - npm install -g nodemon
  - docker build -t muscu-facile-api .
  - docker run --name muscu-facile-api -v $(pwd):/var/www/muscu-facile-api -p 3000:3000 muscu-facile-api
  - docker ps -a

script: docker exec muscu-facile-api npm test
