language: node_js

services:
  - docker

env:
  NODE_ENV: production

before_install:
  - npm install -g nodemon
  - docker build -t muscu-facile-api .
  - docker run --name muscu-facile-api -v $(pwd):/var/www/muscu-facile-api -p 3000:3000 muscu-facile-api
  - docker ps -a

script: docker exec muscu-facile-api npm test
